release-time-graphs-app/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'release_time#index'
  get '/:repo', to: 'release_time#show', as: :repo
end

release-time-graphs-app/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

release-time-graphs-app/app/models/commit.rb
class Commit
  attr_accessor :commit_date, :build_date, :commit_to_release_lead_time, :commit_to_build_lead_time, :sha, :release_date, :release_tag

  def initialize props
    @commit_date = props[:commit_date]
    @build_date = props[:build_date]
    @release_date = props[:release_date]
    @commit_to_build_lead_time = props[:commit_to_build_lead_time]
    @commit_to_release_lead_time = props[:commit_to_release_lead_time]
    @sha = props[:sha]
    @release_tag = props[:release_tag]
  end
end

release-time-graphs-app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

release-time-graphs-app/app/controllers/release_time_controller.rb
require 'csv'
require 'chartkick'
require 'groupdate'
require 'date'

class ReleaseTimeController < ApplicationController

  CSV_FOLDER = 'output'

  def index
    @repos = Dir["#{CSV_FOLDER}/*"].map{|filepath| File.basename(filepath, '.*') }
    return render :error if @repos.nil? || @repos.empty?
  end

  def show
    file = "#{CSV_FOLDER}/#{params['repo']}.csv"
    return render :error unless File.exists?(file)

    @commits = load_commits_from_csv(file)
    @commits_to_plot = @commits.select{|commit| commit.commit_to_release_lead_time < 1000 }
    @commits_to_release_lead_time_graph = @commits_to_plot.map{|commit| [commit.commit_date, commit.commit_to_release_lead_time] }
    @commits_to_build_lead_time_graph = @commits_to_plot.map{|commit| [commit.commit_date, commit.commit_to_build_lead_time] }
    @average_build_lead_time_per_week_graph = average_lead_time_per_week(@commits_to_plot, :commit_to_build_lead_time)
    @average_release_lead_time_per_week_graph = average_lead_time_per_week(@commits_to_plot, :commit_to_release_lead_time)
  end

  def average_lead_time_per_week(commits, tag_type)
    average_lead_time_per_week = []
    weekly_sum = 0
    weekly_count = 0
    current_week_beginning_date = DateTime.now.weeks_ago(1)
    commits.each do |commit|
      lead_time = commit.try tag_type

      if commit.commit_date > current_week_beginning_date
        weekly_sum += lead_time
        weekly_count += 1
      else
        average_lead_time_per_week << [current_week_beginning_date,  weekly_count == 0?  0.00 : weekly_sum/weekly_count]
        weekly_count = 1
        weekly_sum = lead_time
        current_week_beginning_date = current_week_beginning_date.weeks_ago(1)
      end
    end
    average_lead_time_per_week
  end

  def load_commits_from_csv file
    commits = []
    CSV.foreach(file, headers: true) do |commit|
      commits << Commit.new(
        sha: commit['Sha'],
        commit_date: DateTime.parse(commit['Commit date']),
        build_date: DateTime.parse(commit['Build date']),
        release_date: DateTime.parse(commit['Release date']),
        release_tag: commit['Tag'],
        commit_to_release_lead_time: commit['Commit to release (hours)'].to_f.round(2),
        commit_to_build_lead_time: commit['Commit to build(hours)'].to_f.round(2))
    end
    commits
  end
end

release-time-graphs-app/app/helpers/application_helper.rb
module ApplicationHelper
end

release-time-graphs-app/app/helpers/chart_helper.rb
module ChartHelper
  def chart_options additional_options
    {
      library: {
        xAxis: {
          tickInterval: 7*24*60*60*1000
        },
             
        plotOptions: {
          series: {
            marker: {
              enabled: true
            }
          }
        },
        chart: {
          zoomType: 'x'
        }
      }
    }.merge(additional_options)
  end

  def date_format
    '%d-%m-%Y %T'
  end
end

release-time-graphs-app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ReleaseTimeGraphsApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

release-time-graphs-app/app/views/release_time/error.html.erb
<h2>No data generated for any repos. Please edit repo_list.txt and run ./run.sh</h2>

release-time-graphs-app/app/views/release_time/index.html.erb
<h1>Select a repository</h1>

<ul>
  <% @repos.each do |repo| %>
    <li>
      <%= link_to repo, repo_path(repo) %>
    </li>
  <% end %>
</ul>

release-time-graphs-app/app/views/release_time/show.html.erb
<%= line_chart ([{name: "Lead time from commit to Aptly", data: @commits_to_build_lead_time_graph},
  {name: "Lead time from commit to release", data: @commits_to_release_lead_time_graph}]),
               chart_options(
                 title: 'Actual commit lead times',
                 xtitle: 'Commit Time',
                 ytitle: 'Commit Lead Time (in hours)') %>

<%= line_chart ([{name: "Average lead time from commit to Aptly(in hours)", data: @average_build_lead_time_per_week_graph},
  {name: "Average lead time from commit to release(in hours)", data: @average_release_lead_time_per_week_graph}]),
               chart_options(
                 title: 'Average weekly commit lead times',
                 xtitle: 'Weeks',
                 ytitle: 'Commit average lead time (in hours)'
               ) %>

<h1>Commit data</h1>

<table id="commit-table" class="sortable">
  <thead>
    <tr class="heading">
      <th>Sha</th>
      <th>Commit Date</th>
      <th>Build Date</th>
      <th>Release Date</th>
      <th>Release Tag</th>
      <th>Lead Time to Build</th>
      <th>Lead Time to Prod</th>
    </tr>
  </thead>
  <tbody>
    <% @commits.each do |commit| %>
      <tr>
        <td><%= commit.sha %></td>
        <td><%= commit.commit_date.strftime date_format %></td>
        <td><%= commit.build_date.strftime date_format %></td>
        <td><%= commit.release_date.strftime date_format %></td>
        <td><%= commit.release_tag %></td>
        <td><%= commit.commit_to_build_lead_time %></td>
        <td><%= commit.commit_to_release_lead_time %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<script>
  $(document).ready( function () {
    $('#commit-table').DataTable();
  } );
</script>